### ISSUE TITLE
when i use two pictures ,callback has some problems

### ISSUE THREAD

**Issue by heden9** [voronianski/swipe-js-iso#11]
when i use two pictures ,callback has some problems

**Comment by Laslo89** [comment]
yeah, it has. It mainly duplicates the slideds, i think to simulate a valid continous sliding effect when continous===true. The issue is, it also uses 4 indexes and the user sees visually only 2 slides, but we have to work with an index of 4 suddenly. It seems wrong.

**Comment by HwasungKim** [comment]
I have the same issue. on React inspector, it shows that I have two child elements which is correctly intended to be, but then it shows 4 child elements are there on the real dom, regardlessly. My child elements are not just image slides, but complicated nested divs though.

**Comment by wanpan9527** [comment]
So how to solve this problem?

**Comment by postbird** [comment]
same issue
