### ISSUE TITLE
Slivers of next and/or previous slide shown when in a fractional width container 

### ISSUE THREAD

**Issue by erik-inkapool** [voronianski/swipe-js-iso#14]
When in a container with a fractional width (such as 299.5px) the slivers of the next slide (to the right) is shown. 

I have made a tiny reproduction here: https://jsbin.com/zubeyoxono/1/edit?html,css,js,output

**Comment by erik-inkapool** [comment]
@voronianski When do you think there'll be a release of this? If possible before 21st of september would be great for us as we otherwise will have to rely on an internal fork :)

**Comment by voronianski** [comment]
@erik-lundgren new version 2.0.4 is published on npm.
