### ISSUE TITLE
auto-swipe stopped after swipe-left/right by touch at v2.0.4

### ISSUE THREAD

**Issue by mingenesis** [voronianski/swipe-js-iso#17]
Hi voronoanski,
line426    delay = options.auto || 0;
was removed at v2.0.4, cause auto-swipe stopped after swipe-left/right.
@voronianski Please release new version to npm and update react-swipe dependency with this version of swipe-js-iso.

**Comment by geekris1** [comment]
3q

**Comment by YvetteLau** [comment]
the problem still  exists in v2.1.4

**Comment by shurong-kavout** [comment]
The problem still exists in v2.1.5
