### ISSUE TITLE
auto-swipe stopped after swipe-left/right by touch

### ISSUE THREAD

**Issue by shurong-kavout** [voronianski/swipe-js-iso#26]
line222: `delay = 0;` cause auto-swipe stopped after swipe-left/right.

This should be `delay = options.auto || 0;`

![1550544116139](https://user-images.githubusercontent.com/39819734/52986590-04cc8700-3433-11e9-9a49-ae88a71137ee.jpg)

**Comment by Cyberlane** [comment]
I have created a PR with the fix, I will test and merge it tomorrow.

**Comment by xiazhiqiang** [comment]
Hi，@Cyberlane. This issue will cause the problem described by @shurong-kavout. I also encounter this. I try to modified line222 like above. It looks well. So I sincerely ask when this issue can be fixed and merged into master?

**Comment by Cyberlane** [comment]
Fixed, I will create a release within the hour.

**Comment by StarInworld** [comment]
I meet the same problem, i think you have fix it, but not publish new NPM package. When can i use the new Version of 2.1.6?

**Comment by zg1037** [comment]
I have the same problem. When I click the previous page or the next page, the automatic rotation fails. What should I do
