### ISSUE TITLE
Prevent vertical scroll in Safari 10 iOS 10

### ISSUE THREAD

**Issue by bu1ka** [voronianski/swipe-js-iso#7]
In iOS 10 webkit has introduced a new touch event called `touchforcechange`. 
Somehow if you don't have a listener on this event, in `touchmove` the listener will receive the wrong touches.pageY coords and this [check](https://github.com/voronianski/swipe-js-iso/blob/master/swipe.js#L308) will fail and while you are dragging a slide vertical scroll will occur.

NOTE:
I have tried to replace the second argument `function() {}` for this call
`element.addEventListener('touchforcechange', function() {}, false);`
with `noop` from [this](https://github.com/voronianski/swipe-js-iso/blob/master/swipe.js#L20)
but it doesn't work.

So, it would be great if you merged my pr as soon as possible!
And update `react-swipe` deps.

Thanks.

**Comment by doochik** [comment]
@voronianski you've merged PR. Could you please release new version to npm?

**Comment by bu1ka** [comment]
@voronianski Please release new version to npm and update react-swipe dependency with this version of swipe-js-iso.

**Comment by mckinnsb** [comment]
@voronianski I basically had to fork react-swipe because swipe-js-iso has not had a new version released. Please release a new version to NPM.

**Comment by PythonicNinja** [comment]
@voronianski Please release new version 🙇

**Comment by voronianski** [comment]
@PythonicNinja it's released already - `2.0.4`.
